Mojang/minecraft-debugger

src/MCSourceMaps.ts
src/Utils.ts

Paths from VScode setBreakPoint request come in with lower case drive letters but paths from ${workspaceFolder} are upper case. This adds a normalizeDriveLetter api and is used before setting or getting a cached source map by path.
Wrap the `Map<string, MapInfo>` in `MapLookup` which applies `normalizePath` to get/set.

Fix path comparison bug on Windows regarding drive letter case.

---

src/SourceMaps.ts

When source map files are moved (such as when generating a bundle in one location and then deploying it elsewhere), relative paths won't work as expected. In these cases, source maps can be configured using [absolute-resource-path] in their file name template, and the minecraft-debugger should be able to handle these cases.
I also added fallback logic for the bias when getting the generated line number.

Support source map files with absolute paths in the debugger

---

src/Session.ts

Check `sourceMapRoot`, `localRoot` and `generatedSourceMapRoot` for .js files. Provide useful information if .js files cannot be found at those locations.

Better error messaging when .js files cannot be found.

---

package-lock.json
package.json
src/Session.ts
src/SourceMaps.ts
src/extension.ts

- Added new boolean config argument: `inlineSourceMap`. If set to true, TS sourcemaps will be searched through within the outputted JS files.
- - This will add support to [Bridge.](https://github.com/bridge-core/editor), which uses the [Dash compiler](https://github.com/bridge-core/dash-compiler) for compilation, that uses SWC's [wasm-web](https://www.npmjs.com/package/@swc/wasm-web) package for TS transpiration, which can only output inline source-maps.
- Directory paths within config arguments starting with `%localappdata%` (not case-sensitive) will now be replaced with the path to the user's `AppData/Local` directory.
- - This will enable having directory paths to `com.mojang` that aren't restricted to one user.
- Having directories or other irrelevant within the outputted scripts …

add inlineSourceMap arg, parse paths starting with %appdata%, misc bug fixes

---

CHANGELOG.md
package.json
src/Session.ts

Set capability for breakpoint filters at init, enabling the `setExceptionBreakPointsRequest`, which then communicates the option to the debugee (MC).

Add "All Exceptions" toggle to breakpoints panel to optionally enable breaking at exceptions.

---

CHANGELOG.md
package.json
src/Session.ts

If the sourceMapFolder is set but doesn't exist on disk it will throw during discovery. This disrupts the connection handshake and leaves MC waiting for a 'resume' that never arrives.  
Catch the exception, log the error and pop a notification to the user to check their source map folder names.

Handle uncaught exception during .map file discovery.

---

package-lock.json
package.json
src/SourceMaps.ts

As per the spec this field is optional.  I made the code assume the JS file is called `foo.js` if the map is called `foo.js.map`.
https://sourcemaps.info/spec.html
> Line 3: An optional name of the generated code that this source map is associated with.

Fixed source maps which do not include a 'file' field

---

CHANGELOG.md
package-lock.json
package.json
src/ServerDebugAdapterFactory.ts
src/Session.ts
src/StatsProvider.ts
src/extension.ts

Minecraft can push generic "stats" to VSCode, which will display them in tree hierarchy format in the debug panel.

Add stat tree visualizer panel for displaying MC script memory usage.

---

CHANGELOG.md
package-lock.json
package.json
src/Session.ts
src/SourceMaps.ts

The default source map consumer bias of 'least upper bound' does not work in all configurations. Expose this parameter to the launch config. If the designated bias results in a missing line, the alternate will be used.

Expose sourceMapBias config parameter to help fix breakpoint alignment issues between source ts and generated js for certain configurations.

---

CHANGELOG.md
package.json
src/Session.ts

Print events from MC are now all routed through a content log handler, allowing the debugger to be a general purpose content log viewer. Content log handlers add \n to each message, so we don't need to add it on the debugger side.

Remove extra line break in print event, content log adds one from MC.

---

CHANGELOG.md
package.json
src/Session.ts
src/Utils.ts

This change increases the message reliability when multiple add-ons are active in Minecraft. Messages will only be consumed by the add-on indicated by the targetModuleUuid launch parameter. If targetModuleUuid is not defined, a warning will appear on connect.
Given the release cadence differences between the debugger and MC, and the non-breaking protocol change (if MC is lower), protocol handshake will not fail if Debugger version > MC version.  If MC protocol is greater than the debugger, session will terminate with an error indicating the user should update.

Add targetModuleUuid to launch config to isolate debugger messages to a specific add-on.

---

src/SourceMaps.ts

This resolves an issue where, when using inline sourcemaps, if a JS file does not contain an inline source map, `_loadSourceMaps` throws a vague error about the path of `sourceMapRoot`. It now throws an error including the file name that did not have inline source maps.
Old:
New:

Throw error for missing inline source maps

---

CHANGELOG.md
package-lock.json
package.json
src/Session.ts
src/SourceMaps.ts
tsconfig.json

- Added some fun regex code to attempt to replace JS file paths + line numbers with TypeScript source map look-ups.
- Bumped target ES version to 2023 so I can use `String.matchAll`
- Force formatted `SourceMaps.ts` (sorry, not sorry!)

Updated log messages from the game to attempt source map lookups

---

src/Session.ts

- Make log messages slightly clearer by displaying the generated source position relative to the workspace. 
- If there isn't a workspace the absolute path will still be used.
Before:
After:

Make log messages clearer by displaying a relative source path

---

src/Session.ts

Due to an idiosyncrasy with VSCode receiving debugee messages from `console.log`, all the output was being squashed into one large string which prevents the Debug Console from usefully filtering. This adds a small workaround which allows messages sent to the Debug Console to be properly appended as new lines allowing the filter to work for Minecraft scripts using `console.log`.

Fix Debug Console Filtering Issue

---

src/SourceMaps.ts

Made the regex for matching in-line source maps a little less strict.  This is an example of one that would fail to load:
`//# sourceMappingURL=data:application/json;charset=utf8;base64,eyJ2ZXJzaW9uIjozLCJzb3...`

fix(sourcemaps): In-line source maps with charset would fail to be loaded

---

package-lock.json
package.json

Done to indicate that the version in `package.json` is not used.
Recommended here: https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package.jsons-version-not-updated-in-my-repository

chore(packaging): Updated version in package.json to `0.0.0-semantically-released`

---

webview-ui/src/diagnostics_panel/App.css
webview-ui/src/diagnostics_panel/controls/MinecraftStatisticStackedBarChart.tsx
webview-ui/src/diagnostics_panel/controls/MinecraftStatisticStackedLineChart.tsx

Added a tip to stacked line and bar charts to display values of the category being hovered over.
Examples:

feat(diagnostics): Display category value on hover of stacked graph

---

package.json
src/Session.ts

Adds an extension setting `minecraft-debugger.showDiagnosticViewOnConnect` which when true automatically opens the diagnostic view when a complete connection occurs.
If approved possibly worth a mention in the readme?
Resolves #145

feat(diagnostics) Add a extension setting to open the diagnostic view on connection

---

src/Session.ts
src/SourceMaps.ts

If I'm getting this correctly, the absolute path to the original source file should be solved relatively not from the source map root directory, but rather from the source map file's parent directory. A slight nuance that breaks the mapping when using a nested directory structure for the generated source files.
The change required allowing a recursive check of the source map root directory when checking for `.map` files.

fix(typescript): Original source absolute path resolution updates

---

src/Session.ts

In an effort to improve the "it just works" scenarios, this PR presents a QuickPickMenu to the user if the targetModuleUUID is not set (or incorrect) and MC has multiple active add-ons.
- if a targetModuleUUID is set and MC reports having this plugin, no pop up menu
- if target is set and MC does not have this plugin, warn and then show pop with available plugins
- if target is not set but there's only 1 active plugin, connect without menu
- if target is not set and there are multiple active plugins, show pop up menu

feat(debugger): prompt user for target add-on id if not provided and multiple add-ons active in MC.

---

src/SourceMaps.ts

Regex was:
`const inlineSourceMapRegex = /\/\/# sourceMappingURL=data:application\/json;.*;base64,(.*)$/gm;`
Now:
`const inlineSourceMapRegex = /\/\/# sourceMappingURL=data:application\/json;.*base64,(.*)$/gm;`
Remove the semicolon before base64.
Check that the results of mapFileName.split found /scripts/ before indexing the array.

fix(sourcemaps): Fix inline source map regex match pattern if no tags in match string.

---

webview-ui/src/diagnostics_panel/App.tsx
webview-ui/src/diagnostics_panel/controls/StatGroupSelectionBox.tsx

Dropdown disabled until at least one option has been determined.
Dropdown auto-selects the first item in the list.
fixes #144

feat(diagnostics): auto select the first element in the client or plugin dropdowns when opening the diagnostics panel.

---

package.json
src/extension.ts
src/panels/HomeViewProvider.ts

- Adds a vscode command to reload in the command pallete `>Minecraft Diagnostics: Reload MC`
- Added a keyboard shortcut for this `ctrl+shift+r` this can be edited by the user in keyboard shortcuts
- Added a vscode command which allows users to add custom keyboard shortcuts to run commands from `keybindings.json`
- Example `{ "key": "ctrl+shift+t", "command": "minecraft-debugger.runMinecraftCommand", "args": "say hello" },`
- Added an error message if you have an active debug session but try and run an empty command from within the home view
- Launch a debug session of the extension
**Reload**
- Try and run the reload command without a session active an observe the warning message
- Start a debugging session
- Run the reload command from the command pallete, confirm it reloads in game
- …

feat(diagnostics):  Add a reload command and support command keybinds

---

webview-ui/src/diagnostics_panel/App.tsx
webview-ui/src/diagnostics_panel/StatisticResolver.tsx
webview-ui/src/diagnostics_panel/controls/LineChart/LineChart.tsx
webview-ui/src/diagnostics_panel/controls/MinecraftStatisticLineChart.tsx
webview-ui/src/diagnostics_panel/controls/MinecraftStatisticStackedBarChart.tsx
webview-ui/src/diagnostics_panel/controls/MinecraftStatisticStackedLineChart.tsx

It was a bit odd to have frame timing be non-linear!

fix(diagnostics): Updated client timing chart to no longer be sqrt Y scaling

---

README.md
package.json
src/Session.ts
src/SourceMaps.ts
src/panels/HomeViewProvider.ts
webview-ui/src/home_panel/App.tsx
webview-ui/src/home_panel/controls/GeneralSection.tsx

Similar to this PR [here](https://github.com/Mojang/minecraft-debugger/pull/246) but leans into VSCode settings for added flexibility. By using VSCode settings, users can choose to save settings globally or per workspace and it also gives us a place for documentation.
Thanks for the general glob pattern idea Dingsel.  Will this solve your use cases?
- file watching is off by default
- if enabled then both source map clear and /reload happen on source changes.
- if only `localRoot` is defined (no `sourceMapRoot`), the file watch pattern is *.js files from `localRoot`
- if `sourceMapRoot` is defined, the file watch pattern is for *.js and *.map from `sourceMapRoot`
- if `globPattern` is specified, the root is the workspace.
- delay for sending /reload to MC, minimum is 100ms to debounce the …

feat(debugger): Update filewatch to look for .map and .js and send /reload to MC

---

src/Session.ts

Enable file watch on `sourceMapRoot` even if /reload is not enabled.  This ensures the source map cache is always cleared after build.
There are users (editor) that prefer manual /reload in some cases and would need to have updated source maps.
Summary:
- if no source maps, only enable file watch if /reload is enabled (catches .js changes and reloads MC)
- if `globPattern` override is set, enable file watch only if /reload is enabled (this feature was to watch a special pattern)
- if `sourceMapRoot` is set, always enable file watch for .map and .js files but don't send /reload unless enabled.
From the user's perspective nothing has changed. Source maps are simply cleared more aggressively.

fix(debugger): Always filewatch .map and .js from sourceMapRoot, but optionally /reload minecraft.

---

src/session.ts

Maintain a map of source breakpoints per file.  VSCode's `setBreakpointRequest` is triggered per file whenever breakpoints are added or removed.  Since it does not provide all breakpoints for all files, we need to maintain our own record of every breakpoint for every file.  This way, we have all inputs available when constructing the complete list of BPs for a given generated file.

fix(breakpoints): Breakpoints could get overwritten when multiple TS files map to a single JS file.

---

package.json
src/session.ts
src/source-maps.ts

Improve user messaging, including logs and notifications, when working with source maps. 
Output resolved `sourceMapRoot`, `localRoot`, and `generatedSourceRoot` to the debug console on connect. 
Show warning notifications when expected files are not found, like if `sourceMapRoot` is set but it can't find .map files or .js files, or if `sourceMapRoot` is not defined but .ts files are found in local root etc.
Remove `inlineSourceMaps` from package.json, infer inline or external from files found at `sourceMapRoot`. One less thing for the user to configure.
Remove special case for inline source maps when encountering /scripts/ in source folder.
TS Starter pack now works with inline source maps with a one line change in `just.config.ts`:
```
const bundleTaskOptions: BundleTaskParameters = { …
```

fix(source-maps): Improve error messages and logs when working with source maps. 

---

.eslintrc.json
src/config-provider.ts
src/extension.ts
src/message-stream-parser.ts
src/panels/home-view-provider.ts
src/panels/minecraft-diagnostics.ts
src/server-debug-adapter-factory.ts
src/session.ts
src/source-maps.ts
src/stats/replay-stats-provider.test.ts
src/stats/replay-stats-provider.ts
src/stats/stats-provider.ts
src/utilities/getNonce.ts
src/utilities/getUri.ts
src/utils.ts

Defaults are coming from eslint:recommended from this section here:
```
"extends": [
"eslint:recommended",
"plugin:@typescript-eslint/recommended"
],
```
With a few changes specific to the Google style guide and our codebase.
The config for naming conventions is mostly a copy of the default [here](https://typescript-eslint.io/rules/naming-convention#options)
But with a few adjustments to allow snake_case properties, PascalCase globals, and PascalCase enum members.
Eventually we will turn off explicit-any when our protocol messages are properly typed.

fix(lint): adjust eslint settings and fix warnings

---

package.json
src/extension.ts

Adds the existing but unreferenced `minecraft-debugger.runMinecraftCommand` to the command palette when in debug mode as "Minecraft Run Command". Running the command will open an input box to send a command to Minecraft. This can be a simple way of executing one-off commands in addition to the Minecraft Command Shortcuts.

feat: Adds Minecraft Run Command and Reload World on Restart Option
